url: "http://scottdorman.github.io"
baseurl: "/"
title: Scott Dorman
subtitle: Microsoft MVP, Software Architect, Developer, Author
description: Scott Dorman - Microsoft MVP, Software Architect, Developer, Author
feedburner: http://feeds.feedburner.com/ScottDorman

google_analytics: "UA-2662385-1"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/scottdorman_1457462373_45.jpg"
gravatar:
   hash: e74e26bfd345fdd80bedf436178c5829
   size: 80

disqus:
  shortname: "scottdorman-blog"
  show_comment_count: true
   
github:
  repo: https://github.com/scottdorman/scottdorman.github.io

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Scott Dorman
  facebook: scottdorman
  github: scottdorman
  twitter: sdorman
  linkedin: scottorman
  stackoverflow: 1559
  mvp: 4014220
  
# Select which links to show in the footer
footer-links-active:
  mvp: true
  rss: true
  facebook: true
  email: false
  twitter: true
  github: true
  linkedin: true
  stackoverflow: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "http://scottdorman.github.io"  # eg. "deanattali.com/beautiful-jekyll"

# Output options (more information on Jekyll's site)
timezone: "America/New York"
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true
  -
    scope:
      path: ""
      type: "page"
    values:
      nav-include: true  # include in header nav

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
